// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWYMuVVtDKwhadn1ig8uNa2-b45J0geGs',
    appId: '1:40088204340:web:f515b08f8da6e259188661',
    messagingSenderId: '40088204340',
    projectId: 'tiktiktoktok-prac-abc',
    authDomain: 'tiktiktoktok-prac-abc.firebaseapp.com',
    storageBucket: 'tiktiktoktok-prac-abc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVwqHlqenhrgYdDfDeGQ8AoQzEG7xh1F8',
    appId: '1:40088204340:android:79f4f55d30f77d0c188661',
    messagingSenderId: '40088204340',
    projectId: 'tiktiktoktok-prac-abc',
    storageBucket: 'tiktiktoktok-prac-abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjUmFEKa4QGYmUwVEsWlV8OMxM8uiU7F4',
    appId: '1:40088204340:ios:b7c9f9bc5ee03215188661',
    messagingSenderId: '40088204340',
    projectId: 'tiktiktoktok-prac-abc',
    storageBucket: 'tiktiktoktok-prac-abc.appspot.com',
    iosClientId: '40088204340-qj3258ob8ehh1o3quob89lkejich9gp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokFlutter',
  );
}
